# setup_database.py
"""
Purpose: Create and populate a test SQLite database for execution-based NLG evaluation.
This sets up an 'employees' table to test SQL queries generated by NLG models, like in
text-to-SQL tasks. Designed for aspiring scientists to experiment with NLG evaluation.

Dependencies: sqlite3 (built-in with Python)

Usage: Run this file to create an in-memory database. Returns a connection object for use
in other scripts. Can be extended for research by adding more tables or data.

Author: Inspired by Turing’s logic and Curie’s experimental rigor.
"""

import sqlite3


def create_test_database():
    """
    Creates an in-memory SQLite database with an 'employees' table and sample data.
    Returns: Connection object to the database.
    """
    # Create an in-memory database (disappears when program ends, safe for testing)
    conn = sqlite3.connect(":memory:")
    cursor = conn.cursor()

    # Create employees table with id, name, department, and salary
    cursor.execute(
        """
        CREATE TABLE employees (
            id INTEGER PRIMARY KEY,
            name TEXT,
            department TEXT,
            salary INTEGER
        )
    """
    )

    # Insert sample data (like a small lab experiment dataset)
    sample_data = [
        ("Alice", "Sales", 50000),
        ("Bob", "Sales", 55000),
        ("Charlie", "IT", 60000),
        ("Diana", "IT", 65000),
    ]
    cursor.executemany(
        "INSERT INTO employees (name, department, salary) VALUES (?, ?, ?)", sample_data
    )
    conn.commit()

    print("Database created with employees table and sample data.")
    return conn


def test_database(conn):
    """
    Tests the database by querying and printing all employees.
    Helps verify setup, like Curie checking lab equipment.
    """
    cursor = conn.cursor()
    cursor.execute("SELECT * FROM employees")
    rows = cursor.fetchall()
    print("Employees in database:")
    for row in rows:
        print(row)


if __name__ == "__main__":
    # Run setup and test
    conn = create_test_database()
    test_database(conn)
    conn.close()
    print("Database connection closed.")

# Scientist Tip: Extend this by adding more tables (e.g., departments, projects) to
# simulate complex datasets like those in the Spider dataset. Experiment with different
# schemas to test NLG robustness.
